# Generated by Django 5.0 on 2023-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('movie', models.FileField(upload_to='products/movies/%Y/%m/%d', verbose_name='فیلم')),
                ('video_hash', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='هش ویدیو')),
                ('video_size', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سایز ویدیو')),
                ('caption_video', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن ویدیو')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'db_table': 'movies',
            },
        ),
    ]
