# Generated by Django 5.0 on 2023-12-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('place_name', models.TextField(verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان',
                'db_table': 'address_me',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع پیام')),
                ('email', models.EmailField(max_length=155, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('landing_phone', models.CharField(max_length=12, verbose_name='تلفن ثابت')),
                ('address_me', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_me', to='contacts.addressme')),
            ],
            options={
                'verbose_name': 'تلفن همراه',
                'verbose_name_plural': 'تلفن همراه',
                'db_table': 'call_me',
            },
        ),
    ]
