# Generated by Django 5.0 on 2023-12-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نظر')),
                ('text', models.TextField(verbose_name='نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('text', models.TextField(verbose_name='پاسخ سوال')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_user', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_question', to='comments.questions')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نمره')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_comment', to='comments.comments')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرها',
                'db_table': 'rate',
            },
        ),
    ]
