# Generated by Django 5.0 on 2023-12-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('images', '0003_delete_imageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_image', to='images.images'),
        ),
    ]
