# Generated by Django 5.0 on 2023-12-31 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='post',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='job_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
