# Generated by Django 5.0 on 2023-12-31 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('rate_choose', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5, verbose_name='امتیاز')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_post', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment Post',
                'verbose_name_plural': 'Comment Posts',
                'db_table': 'comment_post',
            },
        ),
        migrations.CreateModel(
            name='PostDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_description', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Description',
                'verbose_name_plural': 'Post Descriptions',
                'db_table': 'post_description',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_post', to='images.images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_image', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'db_table': 'post_image',
            },
        ),
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_title_post', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Title',
                'verbose_name_plural': 'Post Titles',
                'db_table': 'post_title',
            },
        ),
    ]
