# Generated by Django 5.0 on 2023-12-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('rate_choose', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5, verbose_name='امتیاز')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_post', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment Post',
                'verbose_name_plural': 'Comment Posts',
                'db_table': 'comment_post',
            },
        ),
    ]
