# Generated by Django 5.0 on 2023-12-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='شناسه انحصاری کالا')),
                ('buy_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت خرید')),
                ('sale_price', models.PositiveBigIntegerField(verbose_name='قیمت فروش')),
                ('num_stock', models.PositiveIntegerField(default=0, verbose_name='تعداد کالا')),
                ('threshold_low_stack', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد نصاب پایین کالا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='products.product')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'stocks',
            },
        ),
    ]
