# Generated by Django 5.0 on 2023-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=155, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=155, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(height_field='height', upload_to='slider/images/%Y/%m/%d', verbose_name='عکس', width_field='width')),
                ('image_hash', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='هش')),
                ('image_size', models.PositiveIntegerField(default=0, verbose_name='حجم عکس')),
                ('alter_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن عکس')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'Image Slider',
                'verbose_name_plural': 'Image Sliders',
                'db_table': 'image_slider',
            },
        ),
    ]
