# Generated by Django 5.0 on 2023-12-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imageslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSlider',
        ),
    ]
