# Generated by Django 5.0 on 2023-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_delete_imageslider'),
        ('products', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='product_images', through='products.ProductImage', to='images.images'),
        ),
    ]
