# Generated by Django 5.0 on 2023-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=True, verbose_name='ارسال دارد'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='disply_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
